deployment:
      tasks:
        - export DEPLOYPATH=/home/maischat/maischathtml/maischat.com/  
        - /bin cp * $DEPLOYPATH                           
        - /bin/cp -r * $DEPLOYPATH                        